version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chmod 777 -R ~
      - run: echo $PWD
      - run: ls -lart
      - run: sudo pear install PHP_CodeSniffer
      - run: composer require --dev --no-update "wp-coding-standards/wpcs"
      - run: composer install --dev --no-autoloader
      - run: sudo phpcs  --config-set installed_paths $PWD/vendor/wp-coding-standards/wpcs
#      - run: phpcs -p -s -v -n --standard=~/repo/.circleci/codesniffer.ruleset.xml .
  notify:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - run: echo $SLACK_WEBHOOK
      - run: curl $CURL_TEST
      - run: curl -X POST -H 'Content-type: application/json' --data '{"text": "This is posted on deployment and comes from *monkey-bot*.", "channel": "#wpphx-github", "link_names": 1, "username": "monkey-bot", "icon_emoji": ":monkey_face:"}' "$SLACK_WEBHOOK"
workflows:  
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - notify:
          requires:
            - build
