version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chmod 777 -R ~
      - run: echo $PWD
      - run: ls -lart
      - run: sudo pear install PHP_CodeSniffer
      - run: composer require --dev --no-update "wp-coding-standards/wpcs"
      - run: composer install --dev --no-autoloader
      - run: sudo phpcs  --config-set installed_paths $PWD/vendor/wp-coding-standards/wpcs
#      - run: phpcs -p -s -v -n --standard=~/repo/.circleci/codesniffer.ruleset.xml .
  notify:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo $SLACK_WEBHOOK
      - run: curl $CURL_TEST
#      - run: curl --request POST --url "$SLACK_WEBHOOK" --data '{"text":"test"}' --header 'Content-type: application/json'
      - run: curl --request POST --url $POSTMAN_ECHO --data 'foo1=bar1&foo2=bar2'
      - run: sudo apt-get install httpie -y
      - run: 
          command: |
              http POST $SLACK_WEBHOOK channel='#wpphx-github' username='CoreCMS-Bot' icon_emoji=':unicorn_face:' \ 
              link_names:=1 \
              attachments:='[{"fallback": "Required plain-text summary of the attachment.", "author_name": "Seth Carstens", "text": "Optional text that appears within the attachment"]'
              
workflows:  
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - notify:
          requires:
            - build
