version: 2.0
machine:
  php:
    version: 7.0.7

dependencies:
  override:
    - composer install --no-interaction --prefer-dist
  pre:
    - sed -i 's/^;//' /opt/circleci/php/$(phpenv global)/etc/conf.d/xdebug.ini

test:
  override:
    - ./vendor/bin/phpcs -p -s -v -n --standard=./codesniffer.ruleset.xml .
