version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo composer self-update
      - run: echo $PWD
      - run: echo ls -lart
      - run: sudo composer require --dev "squizlabs/php_codesniffer"
