version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $PWD
      - run: ls -lart
      - run: composer self-update
      - run: composer require --dev --no-autoloader "squizlabs/php_codesniffer"
